name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Set this to the node version you are using

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Ensure to set VERCEL_TOKEN in your repo secrets
          vercel-org-id: team_eb0SQuBkNmJfPQjQQ1z8CIsu # Find in your Vercel project settings
          vercel-project-id: vercel.com/…5s-projects-51d3cd61/ # Find in your Vercel project settings
          vercel-args: "--prod" # Deploy to production
